### ISSUE TITLE
support for pic16f1947

### ISSUE THREAD

**Issue by mayur-who** [pavius/lpicp#1]
can i use this to program PIC16F1947 ? what modifications i need to do for that?

I think driver code does not need to be changed, am i right?

sorry for sounding like a noob.

**Comment by pavius** [comment]
Probably not. I haven't touched this in years, but the programming protocol varied wildly even between sub-variants of the same family so I would not expect any the 18F code to work on 16F PICs.

**Comment by mayur-who** [comment]
okay, thanks ...
